Web/Epsilon.Web/Areas/Administration/Controllers/CategoryController.cs
using System;
using System.Threading.Tasks;
using Epsilon.Common;
using Epsilon.Services.Data.Contracts;
using Epsilon.Web.Infrastructure.Extensions;
using Epsilon.Web.ViewModels.Category;
using Microsoft.AspNetCore.Mvc;

namespace Epsilon.Web.Areas.Administration.Controllers
{
    public class CategoryController : AdministrationController
    {
        private readonly ICategoryService categoriesService;

        public CategoryController(ICategoryService _categoriesService)
        {
            categoriesService = _categoriesService;
        }

        public async Task<IActionResult> All()
        {
            var model = new CategoryListViewModel()
            {
                Categories = await categoriesService.GetAllWithDeletedAsync<CategoryInListViewModel>(),
            };

            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var inputModel = new CategoryCreateInputModel();

            return View(inputModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CategoryCreateInputModel inputModel)
        {
            if (!this.ModelState.IsValid)
            {
                return View(inputModel);
            }

            try
            {
                await categoriesService.CreateAsync(inputModel, User.Id());

                TempData[GlobalConstants.SuccessMessage] = GlobalConstants.SuccessfullyAddedMessage;

                return RedirectToAction(nameof(All));
            }
            catch (Exception e)
            {
                ModelState.AddModelError(string.Empty, e.Message);

                return View(inputModel);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            try
            {
                var inputModel = await categoriesService.GetOneByIdAsync<CategoryEditInputModel>(id);

                return View(inputModel);
            }
            catch (Exception e)
            {
                return RedirectToAction(nameof(All));
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(CategoryEditInputModel inputModel)
        {
            if (!this.ModelState.IsValid)
            {
                return View(inputModel);
            }

            try
            {
                await categoriesService.EditByIdAsync(inputModel, User.Id());

                TempData[GlobalConstants.SuccessMessage] = GlobalConstants.SuccessfullyChangedMessage;

                return RedirectToAction(nameof(All));
            }
            catch (Exception)
            {
                TempData[GlobalConstants.WarningMessage] = GlobalConstants.UnexpectedError;
                ModelState.AddModelError(string.Empty, "Something went wrong while editing");

                return View(inputModel);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                await categoriesService.DeleteByIdAsync(id);

                TempData[GlobalConstants.SuccessMessage] = GlobalConstants.SuccessfullyRemovedMessage;

                return RedirectToAction(nameof(All));
            }
            catch (Exception)
            {
                TempData[GlobalConstants.WarningMessage] = GlobalConstants.UnexpectedError;
                ModelState.AddModelError(string.Empty, "Something went wrong while deleting");

                return RedirectToAction(nameof(All));
            }
        }
    }
}

Web/Epsilon.Web/Areas/Administration/Controllers/PartController.cs
using Epsilon.Common;
using Epsilon.Services.Data;
using Epsilon.Services.Data.Contracts;
using Epsilon.Web.Infrastructure.Extensions;
using Epsilon.Web.ViewModels.Category;
using Epsilon.Web.ViewModels.Manufacturer;
using Epsilon.Web.ViewModels.Part;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace Epsilon.Web.Areas.Administration.Controllers
{
    public class PartController : AdministrationController
    {

        private readonly IPartService partService;
        private readonly IManufacturerService manufacturerService;

        public PartController(IPartService _partService, IManufacturerService _manufacturerService)
        {
            partService = _partService;
            manufacturerService = _manufacturerService;
        }

        public async Task<IActionResult> All()
        {
            try
            {
                var model = new PartListViewModel()
                {
                    Parts = await partService.GetAllWithDeletedAsync<PartInListViewModel>(),
                };

                return View(model);
            }
            catch (Exception)
            {
                TempData[GlobalConstants.WarningMessage] = GlobalConstants.UnexpectedError;

                return RedirectToAction("All", "Computer");
            }
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            try
            {
                var inputModel = new PartCreateInputModel();

                inputModel.Manufacturers = await manufacturerService.GetAllAsync<ManufacturerDropdownViewModel>();

                return View(inputModel);
            }
            catch (Exception)
            {
                TempData[GlobalConstants.WarningMessage] = GlobalConstants.UnexpectedError;

                return RedirectToAction("All", "Computer");
            }
        }

        [HttpPost]
        public async Task<IActionResult> Create(PartCreateInputModel inputModel)
        {
            if (!this.ModelState.IsValid)
            {
                inputModel.Manufacturers = await manufacturerService.GetAllAsync<ManufacturerDropdownViewModel>();

                return View(inputModel);
            }

            try
            {
                await partService.CreateAsync(inputModel, User.Id());

                TempData[GlobalConstants.SuccessMessage] = GlobalConstants.SuccessfullyAddedMessage;

                return RedirectToAction(nameof(All));
            }
            catch (Exception e)
            {
                inputModel.Manufacturers = await manufacturerService.GetAllAsync<ManufacturerDropdownViewModel>();

                ModelState.AddModelError(string.Empty, e.Message);

                return View(inputModel);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            try
            {
                var inputModel = await partService.GetOneByIdAsync<PartEditInputModel>(id);
                inputModel.Manufacturers = await manufacturerService.GetAllAsync<ManufacturerDropdownViewModel>();


                return View(inputModel);
            }
            catch (Exception e)
            {
                TempData[GlobalConstants.WarningMessage] = GlobalConstants.UnexpectedError;

                return RedirectToAction(nameof(All));
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(PartEditInputModel inputModel)
        {
            if (!this.ModelState.IsValid)
            {
                return View(inputModel);
            }

            try
            {
                await partService.EditByIdAsync(inputModel, User.Id());

                TempData[GlobalConstants.SuccessMessage] = GlobalConstants.SuccessfullyChangedMessage;

                return RedirectToAction(nameof(All));
            }
            catch (Exception)
            {
                TempData[GlobalConstants.WarningMessage] = GlobalConstants.UnexpectedError;
                ModelState.AddModelError(string.Empty, "Something went wrong while editing");

                return View(inputModel);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                await partService.DeleteByIdAsync(id);

                TempData[GlobalConstants.SuccessMessage] = GlobalConstants.SuccessfullyRemovedMessage;

                return RedirectToAction(nameof(All));
            }
            catch (Exception)
            {
                ModelState.AddModelError(string.Empty, "Something went wrong while deleting");
                TempData[GlobalConstants.WarningMessage] = GlobalConstants.UnexpectedError;

                return RedirectToAction(nameof(All));
            }
        }
    }
}

Web/Epsilon.Web/Controllers/CartController.cs
using Epsilon.Common;
using Epsilon.Data.Models;
using Epsilon.Services.Data;
using Epsilon.Services.Data.Contracts;
using Epsilon.Web.Infrastructure.Extensions;
using Epsilon.Web.ViewModels.Cart;
using Epsilon.Web.ViewModels.Computer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace Epsilon.Web.Controllers
{
    [Authorize]
    public class CartController : BaseController
    {
        private readonly ICartService cartService;
        private readonly ICustomerService customerService;

        public CartController(ICartService _cartService, ICustomerService _customerService)
        {
            cartService = _cartService;
            customerService = _customerService;
        }

        public async Task<IActionResult> All(string customerId)
        {
            try
            {
                if (customerId == null)
                {
                    customerId = await customerService.GetCustomerIdAsync(User.Id());
                }

                var model = new CartListViewModel()
                {
                    Computers = await cartService.GetAllComputersOfCustomerCartAsync<ComputerInListViewModel>(customerId),
                };

                return View(model);
            }
            catch (Exception)
            {
                TempData[GlobalConstants.WarningMessage] = GlobalConstants.UnexpectedError;

                return RedirectToAction("All", "Computer");
            }
        }

        public async Task<IActionResult> AddComputer(int id)
        {
            try
            {
                var customerId = await customerService.GetCustomerIdAsync(User.Id());

                if (await customerService.HasCartAsync(customerId) == false)
                {
                    await cartService.CreateCartAsync(customerId);
                }

                var cart = await cartService.GetCartByCustomerIdAsync(customerId);

                await cartService.AddComputerToCartAsync(id, cart.Id);

                return RedirectToAction(nameof(All), new { customerId = customerId });
            }
            catch (ArgumentNullException ae)
            {
                TempData[GlobalConstants.WarningMessage] = ae.Message;

                return RedirectToAction(nameof(All));
            }
        }

        public async Task<IActionResult> Delete(int id)
        {
            var customerId = await customerService.GetCustomerIdAsync(User.Id());

            var cart = await cartService.GetCartByCustomerIdAsync(customerId);

            await cartService.RemoveComputerFromCartAsync(id, cart.Id);

            return RedirectToAction(nameof(All), new { customerId = customerId });
        }
    }
}

Web/Epsilon.Web/Controllers/OrderController.cs
using Epsilon.Common;
using Epsilon.Services.Data;
using Epsilon.Services.Data.Contracts;
using Epsilon.Web.Infrastructure.Extensions;
using Epsilon.Web.ViewModels.Cart;
using Epsilon.Web.ViewModels.Computer;
using Epsilon.Web.ViewModels.Order;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace Epsilon.Web.Controllers
{
    [Authorize]
    public class OrderController : BaseController
    {
        private readonly IOrderService orderService;
        private readonly ICustomerService customerService;
        private readonly ICartService cartService;

        public OrderController(IOrderService _orderService,
            ICustomerService _customerService,
            ICartService _cartService)
        {
            orderService = _orderService;
            customerService = _customerService;
            cartService = _cartService;
        }

        public async Task<IActionResult> All()
        {
            var customerId = await customerService.GetCustomerIdAsync(User.Id());

            var orders = await orderService.GetAllAsync<OrderInListViewModel>(customerId);

            foreach (var order in orders)
            {
                order.Computers = await orderService.GetAllComputersOfOrderAsync<ComputerInListViewModel>(customerId, order.Id);
            }

            var model = new OrderListViewModel()
            {
                Orders = orders,
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CartListViewModel model)
        {
            try
            {
                var customerId = await customerService.GetCustomerIdAsync(User.Id());

                var orderId = await orderService.CreateAsync(customerId, model.Address);

                var computers = await cartService.GetAllComputersOfCustomerCartAsync<ComputerInListViewModel>(customerId);

                foreach (var computer in computers)
                {
                    await orderService.AddComputerToOrderAsync(orderId, computer.Id);
                    TempData[GlobalConstants.SuccessMessage] = GlobalConstants.SuccessfullyAddedMessage;
                }

                await cartService.EmptyAsync(customerId);

                return RedirectToAction(nameof(All));
            }
            catch (Exception)
            {
                TempData[GlobalConstants.ErrorMessage] = GlobalConstants.UnexpectedError;
                return RedirectToAction(nameof(All));
            }
        }
    }
}

Web/Epsilon.Web/Views/Shared/_AdministrationNavBarPartial.cshtml
@using Epsilon.Common
<nav class="navbar navbar-expand-sm navbar-dark bg-dark box-shadow mb-3">
    <div class="container">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@GlobalConstants.SystemName</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="Computer" asp-action="All">All Computers</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-area="Administration" asp-controller="Computer" asp-action="Create">Create Computer</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-area="Administration" asp-controller="Category" asp-action="All">Categories</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-area="Administration" asp-controller="Manufacturer" asp-action="All">Manufacturers</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-area="Administration" asp-controller="Part" asp-action="All">Parts</a>
                </li>
            </ul>
            <partial name="_LoginPartial" />
        </div>
        @*<form class="d-flex">
        <input class="form-control me-sm-2" type="text" placeholder="Search">
        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
        </form>*@
    </div>
</nav>

Web/Epsilon.Web/Views/Shared/_DeleteModalPartial.cshtml
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Delete</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Are you sure you want to delete this item?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <a asp-area="Administration" asp-controller="@ViewData["Controller"]" asp-action="Delete" asp-route-id="@ViewData["Id"]" type="button" class="btn btn-danger">Delete</a>
            </div>
        </div>
    </div>
</div>

Web/Epsilon.Web/Views/Shared/_Layout.cshtml
@using Epsilon.Common
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@this.ViewData["Title"] - @GlobalConstants.SystemName</title>
    <link rel="stylesheet" href="~/css/bootswatchTheme.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/toastr/toastr.min.css" />
    <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="https://kit.fontawesome.com/d638f35ed9.js" crossorigin="anonymous"></script>
</head>
<body>
    <partial name="_UserMessagesPartial" />
    <header >
        @if (User.IsInRole(GlobalConstants.AdministratorRoleName) || User.IsInRole(GlobalConstants.ModeratorRoleName))
        {
            <partial name="_AdministrationNavBarPartial" />
        }
        else
        {
            <partial name="_RegularNavBarPartial" />
        }
    </header>
    
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @this.RenderBody()
        </main>
    </div>
    
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year -  <a href="https://github.com/MartiHr/Epsilon">@GlobalConstants.SystemName</a>
        </div>
    </footer>

    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
    <script src="~/lib/toastr/toastr.min.js"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
    @await this.RenderSectionAsync("Scripts", required: false)
</body>
</html>

Web/Epsilon.Web/Views/Shared/_PagingPartial.cshtml
@model PagingViewModel

<div>
    <ul class="pagination justify-content-center">
        <li class="page-item @(Model.HasPreviousPage ? string.Empty : "disabled")">
            <a class="page-link" asp-action="All" asp-route-id="@Model.PreviousPageNumber">&laquo;</a>
        </li>
        @for (int i = Model.PageNumber - 4; i < Model.PageNumber; i++)
        {
            if (i > 0)
            {
                <li class="page-item ">
                    <a class="page-link" asp-action="All" asp-route-id="@i">@i</a>
                </li>
            }
        }
        <li class="page-item active">
            <a class="page-link" href="#">@Model.PageNumber</a>
        </li>
        @for (int i = Model.PageNumber + 1; i <= Model.PageNumber + 4; i++)
        {
            if (i <= Model.PagesCount)
            {
                <li class="page-item ">
                    <a class="page-link" asp-action="All" asp-route-id="@i">@i</a>
                </li>
            }
        }
        <li class="page-item @(Model.HasNextPage ? string.Empty : "disabled")">
            <a class="page-link" asp-action="All" asp-route-id="@Model.NextPageNumber">&raquo;</a>
        </li>
    </ul>
</div>

Web/Epsilon.Web/Views/Shared/_RegularNavBarPartial.cshtml
@using Epsilon.Common
<nav class="navbar navbar-expand-sm navbar-dark bg-primary box-shadow mb-3">
    <div class="container">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@GlobalConstants.SystemName</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="Computer" asp-action="All">All Computers</a>
                </li>
                @if (User.Identity.IsAuthenticated == true)
                {
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Order" asp-action="All">Orders</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Cart" asp-action="All"><i class="fa-solid fa-cart-shopping"></i></a>
                    </li>
                }     
            </ul>
            <partial name="_LoginPartial" />
        </div>
        @*<form class="d-flex">
        <input class="form-control me-sm-2" type="text" placeholder="Search">
        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
        </form>*@
    </div>
</nav>

Web/Epsilon.Web/Views/Shared/_UserMessages.cshtml
@using Epsilon.Common

@if (TempData[GlobalConstants.ErrorMessage] != null)
{
    <script>
        $(function () { toastr.error('@TempData[GlobalConstants.ErrorMessage].ToString()'); });
    </script>
}

@if (TempData[GlobalConstants.WarningMessage] != null)
{
    <script>
        $(function () { toastr.warning('@TempData[GlobalConstants.WarningMessage].ToString()'); });
    </script>
}

@if (TempData[GlobalConstants.SuccessMessage] != null)
{
    <script>
        $(function () { toastr.success('@TempData[GlobalConstants.SuccessMessage].ToString()'); });
    </script>
}

Web/Epsilon.Web/Views/Shared/_UserMessagesPartial.cshtml
@using Epsilon.Common

@if (TempData[GlobalConstants.ErrorMessage] != null)
{
    <script>
        $(function () { toastr.error('@TempData[GlobalConstants.ErrorMessage].ToString()'); });
    </script>
}

@if (TempData[GlobalConstants.WarningMessage] != null)
{
    <script>
        $(function () { toastr.warning('@TempData[GlobalConstants.WarningMessage].ToString()'); });
    </script>
}

@if (TempData[GlobalConstants.SuccessMessage] != null)
{
    <script>
        $(function () { toastr.success('@TempData[GlobalConstants.SuccessMessage].ToString()'); });
    </script>
}