Web/Epsilon.Web/Controllers/ApplicationUserController.cs
using System.Threading.Tasks;

using Epsilon.Common;
using Epsilon.Data.Models;
using Epsilon.Services.Data.Contracts;
using Epsilon.Web.ViewModels.ApplicationUser;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Epsilon.Web.Controllers
{
    [Authorize]
    public class ApplicationUserController : BaseController
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly SignInManager<ApplicationUser> signInManager;
        private readonly ICustomerService customerService;
        private readonly IEditorService editorService;

        public ApplicationUserController(
                UserManager<ApplicationUser> _userManager,
                SignInManager<ApplicationUser> _signInManager,
                ICustomerService _customerService,
                IEditorService _editorService)
        {
            userManager = _userManager;
            signInManager = _signInManager;
            customerService = _customerService;
            editorService = _editorService;
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult Register()
        {
            if (User?.Identity?.IsAuthenticated ?? false)
            {
                return RedirectToAction("Index", "Home");
            }

            var model = new RegisterViewModel();

            return View(model);
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Register(RegisterViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var user = new ApplicationUser()
            {
                UserName = model.UserName,
                Email = model.Email,
            };

            var result = await userManager.CreateAsync(user, model.Password);

            if (result.Succeeded)
            {
                await customerService.CreateAsync(user.Id);

                TempData[GlobalConstants.SuccessMessage] = "Successfully registered!";

                return RedirectToAction(nameof(Login));
            }

            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }

            return View(model);
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult Login()
        {
            if (User?.Identity?.IsAuthenticated ?? false)
            {
                return RedirectToAction("Index", "Home");
            }

            var model = new LoginViewModel();

            return View(model);
        }


        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var user = await userManager.FindByNameAsync(model.UserName);

            if (user != null)
            {
                var result = await signInManager.PasswordSignInAsync(user, model.Password, false, false);

                if (result.Succeeded)
                {
                    TempData[GlobalConstants.SuccessMessage] = "Successfully logged in!";

                    return RedirectToAction("Index", "Home");
                }
            }

            ModelState.AddModelError(string.Empty, "Invalid login");

            return View(model);
        }

        public async Task<IActionResult> Logout()
        {
            await signInManager.SignOutAsync();

            TempData[GlobalConstants.WarningMessage] = "Logged out!";

            return RedirectToAction("Index", "Home");
        }
    }
}

Web/Epsilon.Web/Views/ApplicationUser/Login.cshtml
@model LoginViewModel

@{
    ViewData["Title"] = "Login";
}

<div class="d-flex justify-content-center align-items-center mt-5">
    <div class="container">
        <div class="row d-flex justify-content-center pt-lg-5">
            <div class="col-12 col-md-8 col-lg-6">
                <div class="border border-3 border-primary"></div>
                <div class="card bg-white shadow-lg">
                    <div class="card-body p-5">
                        <form id="account" method="post" class="mb-3 mt-md-4 ">
                            <h2 class="fw-bold mb-2 text-uppercase ">@ViewData["Title"]</h2>
                            <p class=" mb-5">Please enter your username and password!</p>
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="mb-3">
                                <label asp-for="@Model.UserName" class="form-label"></label>
                                <input asp-for="@Model.UserName" class="form-control" autocomplete="username" aria-required="true" />
                                <span asp-validation-for="@Model.UserName" class="text-danger"></span>
                            </div>
                            <div class="mb-4">
                                <label asp-for="@Model.Password" class="form-label"></label>
                                <input asp-for="@Model.Password" type="password" class="form-control" autocomplete="current-password" aria-required="true" />
                                <span asp-validation-for="@Model.Password" class="text-danger"></span>
                            </div>
                            <div class="d-grid">
                                <button id="login-submit" type="submit" class="btn btn-primary">Log in</button>
                            </div>
                        </form>
                        <div>
                            <p class="mb-0  text-center">
                                Don't have an account? 
                                <a class="nav-link text-primary fw-bold" asp-controller="ApplicationUser" asp-action="Register">Sign Up</a>
                            </p>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Web/Epsilon.Web/Views/ApplicationUser/Register.cshtml
@model RegisterViewModel

@{
    ViewData["Title"] = "Register";
}

<div class="d-flex justify-content-center align-items-center mt-4">
    <div class="container">
        <div class="row d-flex justify-content-center pt-lg-4">
            <div class="col-12 col-md-8 col-lg-6">
                <div class="border border-3 border-primary"></div>
                <div class="card bg-white shadow-lg">
                    <div class="card-body p-5">
                        <form id="account" id="registerForm" method="post" class="mb-3 mt-md-4 ">
                            <h2 class="fw-bold mb-2 text-uppercase ">@ViewData["Title"]</h2>
                            <p class=" mb-5">Please enter your username, email and password!</p>
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="mb-3">
                                <label asp-for="@Model.UserName" class="form-label"></label>
                                <input asp-for="@Model.UserName" class="form-control" autocomplete="username" aria-required="true" />
                                <span asp-validation-for="@Model.UserName" class="text-danger"></span>
                            </div>
                            <div class="mb-3">
                                <label asp-for="@Model.Email" class="form-label"></label>
                                <input asp-for="@Model.Email" class="form-control" autocomplete="username" aria-required="true" />
                                <span asp-validation-for="@Model.Email" class="text-danger"></span>
                            </div>
                            <div class="mb-4">
                                <label asp-for="@Model.Password" class="form-label"></label>
                                <input asp-for="@Model.Password" type="password" class="form-control" autocomplete="current-password" aria-required="true" />
                                <span asp-validation-for="@Model.Password" class="text-danger"></span>
                            </div>
                            <div class="mb-4">
                                <label asp-for="@Model.ConfirmPassword" class="form-label"></label>
                                <input asp-for="@Model.ConfirmPassword" type="password" class="form-control" autocomplete="current-password" aria-required="true" />
                                <span asp-validation-for="@Model.ConfirmPassword" class="text-danger"></span>
                            </div>
                            <div class="d-grid">
                                <button id="register-submit" type="submit" class="btn btn-primary">Register</button>
                            </div>
                        </form>
                        <div>
                            <p class="mb-0  text-center">
                                Already have an account? 
                                <a class="nav-link text-primary fw-bold" asp-controller="ApplicationUser" asp-action="Login">Sign In</a>
                            </p>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@*
<div class="row">
    <div class="col-md-4 offset-md-4">
        <form id="registerForm" method="post">
            <hr />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="text-center mb-3">
                <label asp-for="@Model.UserName">Username</label>
                <input class="form-control " autocomplete="username" aria-required="true" asp-for="@Model.UserName" />
                <span asp-validation-for="@Model.UserName" class="text-danger"></span>
            </div>
            <div class="text-center mb-3">
                <label asp-for="@Model.Email">Email</label>
                <input class="form-control " autocomplete="username" aria-required="true" asp-for="@Model.Email" />
                <span asp-validation-for="@Model.Email" class="text-danger"></span>
            </div>
            <div class="text-center mb-3">
                <label asp-for="@Model.Password">Password</label>
                <input class="form-control" type="password" autocomplete="new-password" aria-required="true" asp-for="@Model.Password" />
                <span asp-validation-for="@Model.Password" class="text-danger"></span>
            </div>
            <div class="text-center mb-3">
                <label asp-for="@Model.ConfirmPassword">Confirm Password</label>
                <input class="form-control" type="password" autocomplete="new-password" aria-required="true" asp-for="@Model.ConfirmPassword" />
                <span asp-validation-for="@Model.ConfirmPassword" class="text-danger"></span>
            </div>
            <div class="text-center">
                <button id="registerSubmit" type="submit" class="btn btn-primary">Register</button>
            </div>
        </form>
    </div>
</div>*@