Web/Epsilon.Web/Controllers/ComputerController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Epsilon.Common;
using Epsilon.Services.Data.Contracts;
using Epsilon.Web.Infrastructure.Extensions;
using Epsilon.Web.ViewModels.Category;
using Epsilon.Web.ViewModels.Computer;
using Epsilon.Web.ViewModels.Manufacturer;
using Epsilon.Web.ViewModels.Part;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;

namespace Epsilon.Web.Controllers
{
    [Authorize]
    public class ComputerController : BaseController
    {
        private readonly IComputerService computerService;
        private readonly ICategoryService categoriesService;
        private readonly IManufacturerService manufacturerService;
        private readonly IEditorService editorService;
        private readonly IPartService partService;
        private readonly IWebHostEnvironment hostEnvironment;

        public ComputerController
            (IComputerService _computerService,
            ICategoryService _categoriesService,
            IManufacturerService _manufacturerService,
            IEditorService _editorService,
            IPartService _partService,
            IWebHostEnvironment _hostEnvironment)
        {
            computerService = _computerService;
            categoriesService = _categoriesService;
            manufacturerService = _manufacturerService;
            editorService = _editorService;
            partService = _partService;
            hostEnvironment = _hostEnvironment;
        }

        [AllowAnonymous]
        public async Task<IActionResult> All(int id = 1)
        {
            if (id <= 0)
            {
                return NotFound();
            }

            const int ItemsPerPage = 4;
            var model = new ComputersListViewModel()
            {
                PageNumber = id,
                ComputersCount = computerService.GetCount(),
                ItemsPerPage = ItemsPerPage,
                Computers = await computerService.GetAllAsync<ComputerInListViewModel>(id, ItemsPerPage),
            };

            return View(model);
        }

        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            try
            {
                var computer = await computerService.GetByIdAsync<ComputerDetailsViewModel>(id);

                return View(computer);
            }
            catch (Exception e)
            {
                TempData[GlobalConstants.ErrorMessage] = e.Message;
                return RedirectToAction(nameof(All));
            }
        }
    }
}

Web/Epsilon.Web/Controllers/HomeController.cs
using System.Diagnostics;
using System.Threading.Tasks;
using Epsilon.Services.Data.Contracts;
using Epsilon.Web.ViewModels;
using Epsilon.Web.ViewModels.Computer;
using Microsoft.AspNetCore.Mvc;

namespace Epsilon.Web.Controllers
{
    public class HomeController : BaseController
    {

        private readonly IComputerService computerService;

        public HomeController(IComputerService _computerService)
        {
            computerService = _computerService;
        }

        public async Task<IActionResult> Index()
        {
            const int itemsCount = 3;

            var model = new ComputersListViewModel()
            {
                Computers = await computerService.GetANumberOfAsync<ComputerInListViewModel>(itemsCount),
            };

            return View(model);
        }

        public IActionResult Privacy()
        {
            return this.View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return this.View(
                new ErrorViewModel { RequestId = Activity.Current?.Id ?? this.HttpContext.TraceIdentifier });
        }
    }
}

Web/Epsilon.Web/Views/Home/Index.cshtml
@model ComputersListViewModel

@{
    this.ViewData["Title"] = "Home Page";
}

<h1 class="text-center">Take a look at our newest additions!</h1>
<hr />


<div class="row">
    @foreach (var computer in Model.Computers)
    {
        <div class="col-md-4 computer-card">
            <div class="card mb-3">
                <h3 class="card-header mb-3">@computer.DisplayName</h3>
                <img src="@computer.ImageUrl" alt="Computer Image" width="100%" height="auto">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">@computer.CPUModel</li>
                    <li class="list-group-item">@computer.GPUModel</li>
                    <li class="list-group-item">@computer.StorageModel</li>
                </ul>
                <div class="card-body text-center">
                    <div class="d-flex justify-content-evenly align-items-center">
                        <span class="align-middle"><b>Price:</b> $@computer.Price.ToString("f2")</span>
                        <a asp-controller="Computer" asp-action="Details" asp-route-id="@computer.Id" class="btn btn-primary text-center">Details</a>
                    </div>
                </div>
            </div>
        </div>
    }
</div>