Web/Epsilon.Web/Areas/Administration/Controllers/ManufacturerController.cs
using Epsilon.Common;
using Epsilon.Services.Data.Contracts;
using Epsilon.Web.Infrastructure.Extensions;
using Epsilon.Web.ViewModels.Category;
using Epsilon.Web.ViewModels.Manufacturer;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace Epsilon.Web.Areas.Administration.Controllers
{
    public class ManufacturerController : AdministrationController
    {
        private readonly IManufacturerService manufacturerService;

        public ManufacturerController(IManufacturerService _manufacturerService)
        {
            manufacturerService = _manufacturerService;
        }

        public async Task<IActionResult> All()
        {
            var model = new ManufacturerListViewModel()
            {
                Manufacturers = await manufacturerService.GetAllWithDeletedAsync<ManufacturerInListViewModel>(),
            };

            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var inputModel = new ManufacturerCreateInputModel();

            return View(inputModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(ManufacturerCreateInputModel inputModel)
        {
            if (!this.ModelState.IsValid)
            {
                return View(inputModel);
            }

            try
            {
                await manufacturerService.CreateAsync(inputModel, User.Id());

                TempData[GlobalConstants.SuccessMessage] = GlobalConstants.SuccessfullyAddedMessage;

                return RedirectToAction(nameof(All));
            }
            catch (Exception e)
            {
                ModelState.AddModelError(string.Empty, e.Message);

                return View(inputModel);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            try
            {
                var inputModel = await manufacturerService.GetOneByIdAsync<ManufacturerEditInputModel>(id);

                return View(inputModel);
            }
            catch (Exception e)
            {
                TempData[GlobalConstants.WarningMessage] = GlobalConstants.UnexpectedError;

                return RedirectToAction(nameof(All));
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(ManufacturerEditInputModel inputModel)
        {
            if (!this.ModelState.IsValid)
            {
                return View(inputModel);
            }

            try
            {
                await manufacturerService.EditByIdAsync(inputModel, User.Id());

                TempData[GlobalConstants.SuccessMessage] = GlobalConstants.SuccessfullyChangedMessage;

                return RedirectToAction(nameof(All));
            }
            catch (Exception)
            {
                TempData[GlobalConstants.WarningMessage] = GlobalConstants.UnexpectedError;
                ModelState.AddModelError(string.Empty, "Something went wrong while editing");

                return View(inputModel);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                await manufacturerService.DeleteByIdAsync(id);

                TempData[GlobalConstants.SuccessMessage] = GlobalConstants.SuccessfullyRemovedMessage;

                return RedirectToAction(nameof(All));
            }
            catch (Exception)
            {
                TempData[GlobalConstants.WarningMessage] = GlobalConstants.UnexpectedError;
                ModelState.AddModelError(string.Empty, "Something went wrong while deleting");

                return RedirectToAction(nameof(All));
            }
        }
    }
}

Web/Epsilon.Web/Areas/Administration/Views/Manufacturer/All.cshtml
@model ManufacturerListViewModel

@{
    ViewData["Title"] = "All manufacturers";
}

<h1 class="text-center">@ViewData["Title"]</h1>

<hr />

<a asp-area="Administration" asp-controller="Manufacturer" asp-action="Create" class="btn btn-success mb-3"><i class="fa-solid fa-plus"></i> Create</a>

<table class="table table-dark table-striped table-hover text-center">
    <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Country</th>
            <th scope="col">Computers Count</th>
            <th scope="col">Parts Count</th>
            <th scope="col">Creation Date</th>
            <th scope="col">Last modified</th>
            <th scope="col">Is Deleted</th>
            <th scope="col">Controls</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var manufacturer in @Model.Manufacturers)
        {
            <tr class="align-middle">
                <td>@manufacturer.Name</td>
                <td>@manufacturer.Country</td>
                <td>@manufacturer.ComputersCount</td>
                <td>@manufacturer.PartsCount</td>
                <td>@manufacturer.CreatedOn</td>
                <td>@(manufacturer.ModifiedOn == null ? "Not modified" : manufacturer.ModifiedOn)</td>
                <td>@manufacturer.IsDeleted</td>
                <td>
                    <div class="d-flex justify-content-evenly">
                        <a asp-area="Administration" asp-action="Edit" asp-route-id="@manufacturer.Id" class="btn btn-sm btn-warning">
                            <i class="fa-solid fa-pen-to-square"></i>
                        </a>
                        <form asp-area="Administration" asp-action="Delete" asp-route-id="@manufacturer.Id">
                            <input type="hidden" value="@manufacturer.Id">
                            <button type="submit" class="btn btn-sm btn-danger">
                                <i class="fa-solid fa-trash"></i>
                            </button>
                        </form>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

Web/Epsilon.Web/Areas/Administration/Views/Manufacturer/Create.cshtml
@model ManufacturerCreateInputModel

@{
    ViewData["Title"] = "Create manufacturer";
}

<div class="form-body h-100">
    <div class="row">
        <div class="form-holder">
            <div class="form-content">
                <div class="form-items">
                    <h3>@ViewData["Title"]</h3>
                    <p>Fill in the data below.</p>
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <form asp-action="Create" method="post" class="mb-3 mt-md-4" enctype="multipart/form-data">
                        <div class="mb-3">
                            <label asp-for="@Model.Name" class="form-label"></label>
                            <input asp-for="@Model.Name" class="form-control" aria-required="true" />
                            <span asp-validation-for="@Model.Name" class="text-danger"></span>
                        </div>
                        <div class="mb-3">
                            <label asp-for="@Model.Country" class="form-label"></label>
                            <input asp-for="@Model.Country" class="form-control" aria-required="true" />
                            <span asp-validation-for="@Model.Country" class="text-danger"></span>
                        </div>
                        <div class="mb-3">
                            <input class="btn btn-primary" type="submit" value="Create" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

Web/Epsilon.Web/Areas/Administration/Views/Manufacturer/Edit.cshtml
@model ManufacturerEditInputModel

@{
    ViewData["Title"] = "Edit manufacturer";
}

<div class="form-body h-100">
    <div class="row">
        <div class="form-holder">
            <div class="form-content">
                <div class="form-items">
                    <h3>@ViewData["Title"]</h3>
                    <p>Fill in the data below.</p>
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <form method="post" class="mb-3 mt-md-4" enctype="multipart/form-data">
                        <input asp-for="@Model.Id" type="hidden" />
                        <div class="mb-3">
                            <label asp-for="@Model.Name" class="form-label"></label>
                            <input asp-for="@Model.Name" class="form-control" aria-required="true" />
                            <span asp-validation-for="@Model.Name" class="text-danger"></span>
                        </div>
                        <div class="mb-3">
                            <label asp-for="@Model.Country" class="form-label"></label>
                            <input asp-for="@Model.Country" class="form-control" aria-required="true" />
                            <span asp-validation-for="@Model.Country" class="text-danger"></span>
                        </div>
                        <div class="mb-3">
                            <input class="btn btn-primary" type="submit" value="Edit" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>